server:
  # 端口
  port: 8080

spring:
  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_java?serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: admin5698

  redis:
    host: 192.168.238.129
    port: 6379
    password: redis5698
    database: 0
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
        max-wait: 10000

  # 文件上传限制
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

# mybatisPlus配置
mybatis-plus:
  # mapper映射地址
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true

upload:
  oss:
    url: https://starsky-blog.oss-cn-guangzhou.aliyuncs.com
    endpoint: oss-cn-guangzhou.aliyuncs.com
    bucketName: starsky-blog
    accessKeyId: LTAI5tFCGAhiR2LDeqZyHPjg
    accesskeySecret: KoGRrOEr9jPwbpO2wnRPFZSjnqvcG3
